# Generated by Django 4.1.4 on 2023-02-17 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentComplex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('class_type', models.CharField(max_length=16)),
                ('image', models.ImageField(upload_to='images/complexes/')),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('liter_name', models.CharField(max_length=32)),
                ('districts', models.CharField(max_length=32)),
                ('meter_price', models.IntegerField()),
                ('price', models.IntegerField()),
                ('sale_price', models.IntegerField(null=True)),
                ('url', models.URLField()),
                ('image', models.ImageField(upload_to='images/flats/')),
                ('square', models.FloatField()),
                ('living_square', models.FloatField()),
                ('apartment_complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.apartmentcomplex')),
            ],
        ),
    ]
