# Generated by Django 4.1.4 on 2023-02-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='coefficient',
            field=models.FloatField(default=0),
        ),
    ]
